config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resources :projects do
    resources :user_stories
    resources :sprints do
      resources :user_story_sprint_mappings, only: [:index, :create, :new, :destroy]
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/models/user_story.rb
class UserStory < ApplicationRecord
  belongs_to :project
  has_many :user_story_sprint_mappings, dependent: :destroy

  validates :title, presence: true
  validates :title, length: { minimum: 3, maximum: 100 }
  validates :description, length: { maximum: 1000 }
  validates :estimate, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  enum status: { not_started: 0, in_progress: 1, completed: 2, cancelled: 3, paused: 4 }

  before_validation :set_default_status, on: :create

  def set_default_status
    self.status ||= :not_started
  end

end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project

  def index
    @user_stories = @project.user_stories.order(:title)
  end
  
  def new
    @user_story = @project.user_stories.new
  end

  def create
    @user_story = @project.user_stories.new(user_story_params)
    if @user_story.save
      flash[:notice] = "User story was successfully created"
      redirect_to project_user_stories_path(@project)
    else
      render :new
    end
  end

  def edit
    @user_story = @project.user_stories.find(params[:id])
  end

  def update
    @user_story = @project.user_stories.find(params[:id])
    if @user_story.update(user_story_params)
      flash[:notice] = "User story was successfully updated"
      redirect_to project_user_stories_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @user_story = @project.user_stories.find(params[:id])
    @user_story.destroy
    flash[:notice] = "User story was successfully deleted"
    redirect_to project_user_stories_path(@project)
  end

  private

  def user_story_params
    params.require(:user_story).permit(:title, :description, :status, :estimate)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/user_stories_helper.rb
module UserStoriesHelper
end

app/views/user_stories/edit.html.haml
%h1 UserStories#Edit

= form_for [@project, @user_story] do |f|
  .field
    = f.label :title
    = f.text_field :title

  .field
    = f.label :description
    = f.text_area :description

  .field
    = f.label :estimate
    = f.text_area :estimate

  .actions
    = f.submit

= link_to 'Back', project_user_stories_path(@project)

app/views/user_stories/index.html.haml
%h1= "User Stories for  #{@project.name}"

- if @user_stories.empty?
    %p No user story. Do you want to create some?
- else
    %table
        %thead
            %tr
                %th Title
                %th Description
                %th Status
                %th Actions
        %tbody
        - @user_stories.each do |user_story|
            %tr
                %td= user_story.title
                %td= user_story.description
                %td= user_story.status
                %td
                    = link_to 'Edit', edit_project_user_story_path(@project, user_story)
                    = link_to 'Delete', project_user_story_path(@project, user_story), method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New User Story', new_project_user_story_path

app/views/user_stories/new.html.haml
-# app/views/user_stories/new.html.haml

%h1 New User Story

= form_for [@project, @user_story] do |f|
  .field
    = f.label :title
    = f.text_field :title

  .field
    = f.label :description
    = f.text_area :description

  .field
    = f.label :estimate
    = f.text_area :estimate

  .actions
    = f.submit

= link_to 'Back', project_user_stories_path(@project)

app/views/user_stories/show.html.haml
%h1 UserStories#show
%p Find me in app/views/user_stories/show.html.haml