config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resources :projects do
    resources :user_stories
    resources :sprints do
      resources :user_story_sprint_mappings, only: [:index, :create, :new, :destroy]
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  belongs_to :project
  has_many :user_story_sprint_mappings, dependent: :destroy

  validates :name, presence: true
  validates :description, length: { maximum: 1000 }
  validates_uniqueness_of :name, scope: :project_id

  # If the sprint is active, there must be a start date.
  validates :start_date, presence: true, if: :active?
  
  # If the sprint has an end date, it must be after the start date.
  validates_date :end_date, after: :start_date, allow_blank: true

  before_validation :set_default_active, on: :create

  private

  def set_default_active
    self.active ||= false
  end

end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project

  def index
    @sprints = @project.sprints.order(:start_date)
  end

  def new
    @sprint = @project.sprints.new
  end

  def create
    @sprint = @project.sprints.new(sprint_params)
    if @sprint.save
      flash[:notice] = "Sprint was successfully created"
      redirect_to project_sprints_path(@project)
    else
      render :new
    end
  end

  def edit
    @sprint = @project.sprints.find(params[:id])
  end

  def update
    @sprint = @project.sprints.find(params[:id])
    if @sprint.update(sprint_params)
      flash[:notice] = "Sprint was successfully updated"
      redirect_to project_sprints_path(@project)
    else
      render :edit
    end
  end

  def show
    @sprint = @project.sprints.find(params[:id])
  end

  def destroy
    @sprint = @project.sprints.find(params[:id])
    @sprint.destroy
    flash[:notice] = "Sprint was successfully deleted"
    redirect_to project_sprints_path(@project)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def sprint_params
    params.require(:sprint).permit(:name, :description, :start_date, :end_date, :active)
  end

end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/sprints/edit.html.haml
%h1 Edit Sprint

= form_for [@project, @sprint] do |f|
  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :description
    = f.text_area :description

  .field
    = f.label :start_date
    = f.date_select :start_date

  .field
    = f.label :end_date
    = f.date_select :end_date

  .actions
    = f.submit

= link_to 'Back', project_sprints_path(@project)

app/views/sprints/index.html.haml
-# app/views/sprints/index.html.haml

%h1 Sprints

- if @sprints.size > 0
  %table
    %thead
      %tr
        %th Name
        %th Description
        %th Active
        %th Start Date
        %th Actions
    %tbody
    - @sprints.each do |sprint|
      %tr
        %td= sprint.name
        %td= sprint.description
        %td= sprint.active
        %td= sprint.start_date
        %td
          = link_to 'Show', project_sprint_path(@project, sprint)
          = link_to 'Edit', edit_project_sprint_path(@project, sprint)
          = link_to 'Delete', project_sprint_path(@project, sprint), method: :delete, data: { confirm: 'Are you sure?' }
- else
  %p No sprint.  Do you want to create some?


= link_to 'New Sprint', new_project_sprint_path(@project)

app/views/sprints/new.html.haml
%h1 New Sprint

= form_for [@project, @sprint] do |f|
  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :description
    = f.text_area :description

  .field
    = f.label :start_date
    = f.date_select :start_date

  .field
    = f.label :end_date
    = f.date_select :end_date

  .actions
    = f.submit

= link_to 'Back', project_user_stories_path(@project)

app/views/sprints/show.html.haml
%h1= @sprint.name

%p
  %b Description:
  = @sprint.description

%p
  %b Active:
  = @sprint.active

%p
  %b Start Date:
  = @project.start_date

%ul
  %li
    = link_to 'Sprint Backlog', project_sprint_user_story_sprint_mappings_path(@project, @sprint)
  %li
    = link_to 'Back', projects_path