config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resources :projects do
    resources :user_stories
    resources :sprints do
      resources :user_story_sprint_mappings, only: [:index, :create, :new, :destroy]
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/models/project.rb
# Create Project model
class Project < ApplicationRecord

    enum status: { not_started: 0, in_progress: 1, completed: 2, cancelled: 3, paused: 4 }
 
    # Associations
    belongs_to :account
    has_many :user_stories, dependent: :destroy
    has_many :sprints, dependent: :destroy
    
    # Name of the project (unique and min length of 3 and max lenght of 100)
    validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
 
    # Description of the project (max length of 1000)
    validates :description, length: { maximum: 1000 }

    # Start date of the project (optional when status is not_started, required otherwise)
    validate :start_date_required_when_started

    # End date of the project (optional but if present it must be after start_date)
    validates_date :end_date, after: :start_date, allow_blank: true

    # Status of the project (not_started, in_progress, completed, cancelled, paused)
    validates :status, presence: true, inclusion: { in: Project.statuses.keys }
 
    # Scopes
    scope :not_started, -> { where(status: 'not_started') }
    scope :in_progress, -> { where(status: 'in_progress') }
    scope :completed, -> { where(status: 'completed') }
    scope :cancelled, -> { where(status: 'cancelled') }
    scope :paused, -> { where(status: 'paused') }
 
    # Callbacks
    before_validation :set_default_status, on: :create
 
    # Methods
    def set_default_status
      self.status ||= :not_started
    end

    def unmapped_user_stories
      UserStory.joins("LEFT JOIN user_story_sprint_mappings ON user_stories.id = user_story_sprint_mappings.user_story_id")
               .where("user_story_sprint_mappings.id IS NULL AND user_stories.project_id = ?", self.id)
    end
    
    private

    def start_date_required_when_started
        if status != "not_started" && start_date.blank?
          errors.add(:start_date, "is required when status is '#{status}'")
        end
    end 
      
  end

app/controllers/projects_controller.rb
# app/controllers/projects_controller.rb

class ProjectsController < ApplicationController

    before_action :authenticate_user!

    def index
      # Get all projects sorted by name
      @projects = Project.order(:name)
    end
  
    def show
      @project = Project.find(params[:id])
    end
  
    def new
      @project = Project.new
    end
  
    def create
      @project = Project.new(project_params)
      @project.account = current_user.account
      if @project.save
        # Redirect to the project's show page and display flash message
        flash[:notice] = "Project was successfully created"
        redirect_to @project
      else
        render :new
      end
    end
  
    def edit
      @project = Project.find(params[:id])
    end
  
    def update
      @project = Project.find(params[:id])
      if @project.update(project_params)
        flash[:notice] = "Project was successfully updated"
        redirect_to @project
      else
        render :edit
      end
    end
  
    def destroy
      @project = Project.find(params[:id])
      @project.destroy
      flash[:notice] = "Project #{@project.name} was successfully deleted"
      redirect_to projects_path
    end
  
    private
  
    def project_params
      params.require(:project).permit(:name, :description, :status, :start_date)
    end
  end

app/views/projects/_form.html.haml
-# app/views/projects/_form.html.haml

= form_for project do |f|
  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :description
    = f.text_area :description

  .field
    = f.label :status
    = f.select :status, Project.statuses.keys.map { |status| [status.humanize, status] }

  .field
    = f.label :start_date
    = f.date_select :start_date

app/views/projects/_project_list.html.haml
%div{ class: 'relative overflow-x-auto shadow-md sm:rounded-lg' }
  %table{ class: 'w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400' }
    = render partial: 'layouts/table_header', locals: { header_names: [ 'Name', 'Description', 'Status', 'Start Date', 'End Date' ] }
    %tbody
      - projects.each do |project|
        %tr{ class: 'odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700' }
          %td{ class: 'px-6 py-4' }= link_to project.name, project_path(project)
          %td{ class: 'px-6 py-4' }= project.description
          %td{ class: 'px-6 py-4' }= project.status.humanize
          %td{ class: 'px-6 py-4' }= project.start_date
          %td{ class: 'px-6 py-4' }= project.end_date

app/views/projects/edit.html.haml
- content_for :work_header_title do
  = "Edit #{ @project.name }"
- content_for :work_header_actions do
  = button('Back', projects_path, :alternate, :normal)
  %input{ type: "submit", value: "Save", form: "edit_project_#{@project.id}", class: button_class(:primary, :normal) }

= render 'form', project: @project

app/views/projects/index.html.haml
- content_for :work_header_title do
  Projects
- content_for :work_header_actions do
  = button('Back', projects_path, :alternate, :normal)
  = button('New Project', new_project_path)

- if @projects.size > 0
  = render partial: 'project_list', locals: { projects: @projects }
- else
  %p No project.  You can create one.

app/views/projects/new.html.haml
- content_for :work_header_title do
  New Project
- content_for :work_header_actions do
  = button('Back', projects_path, :alternate, :normal)
  %input{ type: "submit", value: "Save", form: "new_project", class: button_class(:primary, :normal) }


= render 'form', project: @project

app/views/projects/show.html.haml
- content_for :work_header_title do
  = "Project #{@project.name}"
- content_for :work_header_actions do
  = button('Edit', edit_project_path(@project))
  = link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: button_class(:alternate, :normal)
  = button('Back', projects_path, :alternate, :normal)

%p
  %b Description:
  = @project.description

%p
  %b Status:
  = @project.status.humanize

%p
  %b Start Date:
  = @project.start_date

%ul
  %li
    = link_to 'User Stories', project_user_stories_path(@project)
  %li
    = link_to 'Sprints', project_sprints_path(@project)