config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resources :projects do
    resources :user_stories
    resources :sprints do
      resources :user_story_sprint_mappings, only: [:index, :create, :new, :destroy]
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/models/user_story_sprint_mapping.rb
class UserStorySprintMapping < ApplicationRecord
  belongs_to :user_story
  belongs_to :sprint

  validates :user_story, uniqueness: true
end

app/controllers/user_story_sprint_mappings_controller.rb
class UserStorySprintMappingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_sprint

  def index
    @user_story_sprint_mappings = @sprint.user_story_sprint_mappings
  end

  def new
    @user_story_sprint_mapping = UserStorySprintMapping.new
    @user_stories = @project.unmapped_user_stories    
  end

  def create
    @user_story_sprint_mapping = UserStorySprintMapping.new(user_story_sprint_mapping_params)
    @user_story_sprint_mapping.sprint = @sprint
    if @user_story_sprint_mapping.save
      redirect_to project_sprint_user_story_sprint_mappings_path(@project, @sprint), notice: 'User story was successfully mapped to sprint.'
    else
      @user_stories = @project.unmapped_user_stories
      render :new
    end
  end

  def destroy
    @user_story_sprint_mapping = UserStorySprintMapping.find(params[:id])
    @user_story_sprint_mapping.destroy
    redirect_to project_sprint_user_story_sprint_mappings_path(@project, @sprint), notice: 'User story was successfully unmapped from sprint.'
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_sprint
    @sprint = Sprint.find(params[:sprint_id])
  end

  def user_story_sprint_mapping_params
    params.require(:user_story_sprint_mapping).permit(:user_story_id)
  end

end

app/helpers/user_story_sprint_mappings_helper.rb
module UserStorySprintMappingsHelper
end

app/views/user_story_sprint_mappings/create.html.haml
%h1 UserStorySprintMappings#create
%p Find me in app/views/user_story_sprint_mappings/create.html.haml

app/views/user_story_sprint_mappings/destroy.html.haml
%h1 UserStorySprintMappings#destroy
%p Find me in app/views/user_story_sprint_mappings/destroy.html.haml

app/views/user_story_sprint_mappings/index.html.haml
%h1= "User Story Sprint Mappings for #{@sprint.name}"

- if @user_story_sprint_mappings.empty?
    %p No user story assigned to sprint. Do you want to assign some?
- else
    %table
        %thead
            %tr
                %th User Story
                %th Actions
        %tbody
        - @user_story_sprint_mappings.each do |mapping|
            %tr
                %td= mapping.user_story.title
                %td= mapping.sprint.name
                %td
                    = link_to 'Delete', project_sprint_user_story_sprint_mapping_path(@project, @sprint, mapping), method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New User Story Sprint Mapping', new_project_sprint_user_story_sprint_mapping_path(@project, @sprint)

app/views/user_story_sprint_mappings/new.html.haml
%h1 UserStorySprintMappings#new

= form_for [@project, @sprint, @user_story_sprint_mapping] do |f|
    .field
        = f.label :user_story_id
        = f.collection_select :user_story_id, @project.unmapped_user_stories, :id, :title, prompt: "Select a user story"

    .actions
        = f.submit "Create User Story Sprint Mapping"